// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPzZOd0AUUz5c_VvO5e2WZxY-1o6ADuVg',
    appId: '1:151377962655:web:de2dc0642f76a9b89fe4aa',
    messagingSenderId: '151377962655',
    projectId: 'financialapp-2ab20',
    authDomain: 'financialapp-2ab20.firebaseapp.com',
    storageBucket: 'financialapp-2ab20.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX2y0jfr9Rtj_NEHYLjDQJLcdlJsHSX4I',
    appId: '1:151377962655:android:faa02cd82604784f9fe4aa',
    messagingSenderId: '151377962655',
    projectId: 'financialapp-2ab20',
    storageBucket: 'financialapp-2ab20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB27f5Wv5ZrWo8CvPZFAgj17yRO03bTiLw',
    appId: '1:151377962655:ios:a1d38043dc79caf49fe4aa',
    messagingSenderId: '151377962655',
    projectId: 'financialapp-2ab20',
    storageBucket: 'financialapp-2ab20.appspot.com',
    iosBundleId: 'com.example.financialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB27f5Wv5ZrWo8CvPZFAgj17yRO03bTiLw',
    appId: '1:151377962655:ios:e7b08cc7f051387f9fe4aa',
    messagingSenderId: '151377962655',
    projectId: 'financialapp-2ab20',
    storageBucket: 'financialapp-2ab20.appspot.com',
    iosBundleId: 'com.example.financialApp.RunnerTests',
  );
}
